# Tahap 1: Memasak (Build)
FROM rust:1.75-slim-bookworm as builder
WORKDIR /app
COPY . .
RUN cargo build --release

# Tahap 2: Menyajikan (Run)
FROM debian:bookworm-slim
WORKDIR /app
# Kita butuh library OpenSSL supaya bisa konek ke Neon (HTTPS)
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/scanner-worker .

# Buka port 8080 (Untuk health check Koyeb)
EXPOSE 8080

CMD ["./scanner-worker"]