# Tahap 1: Build (Memasak kode jadi aplikasi)
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy file dependency dulu biar cache-nya awet
COPY go.mod go.sum ./
RUN go mod download

# Copy semua kode sumber
COPY . .

# Build aplikasinya jadi file bernama 'server'
RUN go build -o server main.go

# Tahap 2: Run (Menjalankan di container kecil biar ringan)
FROM alpine:latest

WORKDIR /root/

# Ambil hasil build dari Tahap 1
COPY --from=builder /app/server .

# Buka port 8080
EXPOSE 8080

# Jalankan servernya
CMD ["./server"]