# ========================
# TAHAP 1: Masak Golang (API)
# ========================
FROM golang:1.23-alpine AS go-builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server main.go

# ========================
# TAHAP 2: Masak Rust (Worker)
# ========================
# Kita butuh image Rust
FROM rust:1.75-slim-bookworm as rust-builder
WORKDIR /app
# Kita copy source code Rust dari folder scanner-worker
# (Nanti kita atur context-nya di Koyeb biar bisa lihat folder sebelah)
COPY scanner-worker/ . 
RUN cargo build --release

# ========================
# TAHAP 3: Sajikan (Final Image)
# ========================
FROM debian:bookworm-slim

WORKDIR /app

# Install library penting (SSL & CA Certificates) biar bisa konek DB
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*

# Ambil hasil masakan Golang
COPY --from=go-builder /app/server .
COPY --from=go-builder /app/start.sh .

# Ambil hasil masakan Rust
COPY --from=rust-builder /app/target/release/scanner-worker .

# Beri izin eksekusi ke script start.sh
RUN chmod +x start.sh

# Buka port 8080 (Pintu utama)
EXPOSE 8080

# Jalankan Mandor!
CMD ["./start.sh"]